import React, {useMemo} from 'react';
import * as THREE from 'three';
import {Line} from '@react-three/drei';
import {compileCurve,compileSurface,evaluateConstant,parseTuple} from '../lib/math.js';

function PointObject({object,onHover}){const p=parseTuple(object.value);return <mesh position={p} onPointerMove={e=>{e.stopPropagation();onHover(e.point);}} onPointerOut={()=>onHover(null)}><sphereGeometry args={[.11,20,20]}/><meshStandardMaterial color={object.color}/></mesh>;}

function VectorObject({object,onHover}){const [x,y,z]=parseTuple(object.value);const end=new THREE.Vector3(x,y,z);const len=end.length();const dir=end.clone().normalize();const q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),dir);return <group><Line points={[[0,0,0],[x,y,z]]} color={object.color} lineWidth={3} onPointerMove={e=>{e.stopPropagation();onHover(e.point);}} onPointerOut={()=>onHover(null)}/>{len>0&&<mesh position={end} quaternion={q} onPointerMove={e=>{e.stopPropagation();onHover(e.point);}} onPointerOut={()=>onHover(null)}><coneGeometry args={[.12,.35,18]}/><meshStandardMaterial color={object.color}/></mesh>}</group>;}

function SurfaceObject({object,onHover}){const geometry=useMemo(()=>{const fn=compileSurface(object.value);const n=45,min=-5,max=5,g=new THREE.BufferGeometry(),pos=[],idx=[];for(let j=0;j<=n;j++)for(let i=0;i<=n;i++){const x=min+(max-min)*i/n,y=min+(max-min)*j/n,z=fn(x,y);pos.push(x,y,Number.isFinite(z)?Math.max(-20,Math.min(20,z)):0);}for(let j=0;j<n;j++)for(let i=0;i<n;i++){const a=j*(n+1)+i,b=a+1,c=a+n+1,d=c+1;idx.push(a,b,d,a,d,c);}g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();return g;},[object.value]);return <mesh geometry={geometry} onPointerMove={e=>{e.stopPropagation();onHover(e.point);}} onPointerOut={()=>onHover(null)}><meshStandardMaterial color={object.color} side={THREE.DoubleSide} transparent opacity={.68}/></mesh>;}

function CurveObject({object,onHover}){const points=useMemo(()=>{const fn=compileCurve(object.value);const min=evaluateConstant(object.tMin);const max=evaluateConstant(object.tMax);if(!Number.isFinite(min)||!Number.isFinite(max)||min===max)return [];const n=300;const result=[];for(let i=0;i<=n;i++){const t=min+(max-min)*i/n;const [x,y,z]=fn(t);if([x,y,z].every(Number.isFinite))result.push([x,y,z]);}return result;},[object.value,object.tMin,object.tMax]);if(points.length<2)return null;return <Line points={points} color={object.color} lineWidth={3} onPointerMove={e=>{e.stopPropagation();onHover(e.point);}} onPointerOut={()=>onHover(null)}/>;}

export default function SceneObjects({objects,onHover}){return <>{objects.filter(o=>o.visible).map(o=>{try{if(o.type==='point')return <PointObject key={o.id} object={o} onHover={onHover}/>;if(o.type==='vector')return <VectorObject key={o.id} object={o} onHover={onHover}/>;if(o.type==='curve')return <CurveObject key={o.id} object={o} onHover={onHover}/>;return <SurfaceObject key={o.id} object={o} onHover={onHover}/>;}catch{return null;}})}</>;}